### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by andybui01** [andybui01/sel4cp#1]
- [ ] sel4cp tool support
    - [ ] Decouple monitor into init + monitor, embed a monitor per partition
    - [ ] Use PD hierarchy changes for the monitor. Each monitor will be the parent/root PD of a partition.
    - [ ] Remove amount of build artifacts, create temporary folders in top level dir instead of sel4cp repo
- [ ] [FRWY-LS1012A-PB](https://www.nxp.com/design/qoriq-developer-resources/layerscape-frwy-ls1012a-board:FRWY-LS1012A) board support (@kswin01)
- [ ] Basic partition cache coloring
